### ISSUE TITLE
小度接入口，感觉app里面开关状态无法同步。打开开关之后 过一会自动变成关的状态。 

### ISSUE THREAD

**Issue by jwister** [larry-wong/bemfa#11]
小度接入口，感觉app里面开关状态无法同步。打开开关之后 过一会自动变成关的状态。 但是实际开关并没有关。或者关闭开关之后。立马继续点关闭。他一直都发开的状态,导致发送的指令一直是off   。

**Comment by onwebbe** [comment]
我这儿也发现了同样的问题。小度灯、开关 状态没有办法同步到小度里面。

**Comment by jwister** [comment]
您的邮件已收到，谢谢。

**Comment by onwebbe** [comment]
感觉是bamfa云本身的问题。我试了一下bemfa的tcp 云。用了推荐的代码。发现也有这个问题。

**Comment by 616734202** [comment]
跟巴法云客服联系过，说是小度没有及时获取设备状态信息，让我在他们巴法云小程序用，估计暂时解决不了。

**Comment by larry-wong** [comment]
不属于此插件问题，先关闭。
