### ISSUE TITLE
能否将温湿度两个实体结合同步至巴法云？

### ISSUE THREAD

**Issue by micturkey** [larry-wong/bemfa#13]
举个例子，当前模式下，客厅温度的数据为#30，客厅湿度的数据为##30
对于小爱音箱，你问他客厅温度，他会回答你 客厅温度温度 是30度，但是问湿度就是0%了，要想问湿度，就得问他，客厅湿度湿度是多少。
所以，能否将温湿度两个传感器结合起来，数据直接设置为#30#30呢

**Comment by larry-wong** [comment]
v1.3.0 版本支持将环境传感器以区域的维度合并成一个巴法云设备。
