### ISSUE TITLE
小米温湿度计2 小爱同学汇报温度的时候为0℃

### ISSUE THREAD

**Issue by kettly1260** [larry-wong/bemfa#20]
温湿度计2在homeassistant上温湿度是两个不同的实例，转换到巴法之后温度是#Temp，这个没有问题，但是湿度实例的格式是##Humidity。这个里面我看了bemfa的定义里面温度是不能省略的，因此会汇报一个0℃的温度。如果只在小爱询问温度是多少，小爱同学会自动识别湿度实例对应的温度而不是温度实例对应的温度。不知道能不能统一两个实例到同一个标签从而解决这个问题

**Comment by larry-wong** [comment]
v1.3.0 版本支持将环境传感器以区域的维度合并成一个巴法云设备。
