### ISSUE TITLE
什么时候可以参考小米miot插件通过集成可以进行配置的?

### ISSUE THREAD

**Issue by jyz0501** [larry-wong/bemfa#21]
每次删除和重新同步,音响那边还要再重新配置实体名称和位置,非常麻烦

**Comment by kukudemajia** [comment]
这个确实是很麻烦，小一百的设备每次更改要崩溃

**Comment by larry-wong** [comment]
v1.2.0 版本已支持修改同步后的设备名称。
待巴法云支持位置设置后，可考虑将位置信息自动带过去。
