### ISSUE TITLE
能否增加一个选项，无论什么状态都执行？

### ISSUE THREAD

**Issue by wolnlow** [larry-wong/bemfa#22]
通过其他方式打开设备，而小爱同学以自身上次打开状态为准，致使当前无法通过小爱关闭设备，必须先让小爱执行打开，再执行关闭。因此能否增加一个选项，无论当前设备状态，都直接执行。

**Comment by larry-wong** [comment]
HA 设备状态的改变会同步至小爱同学。
目前比较好的方式是在“其他方式打开设备”的场景下，想办法将设备状态同步至 HA.
当前增加一个此类选项的优先级不太高，后续需求较多时可以考虑支持。
