### ISSUE TITLE
天猫精灵控制灯组的时候, 提示智能家居服务暂时不能用?  单个灯控制没有, 用group做成灯组就说不能控制了. 

### ISSUE THREAD

**Issue by WalterDSU** [larry-wong/bemfa#23]
天猫精灵控制HA创建的灯组的时候, 提示智能家居服务暂时不能用?  单个灯控制没有, 在HA用group做成灯组就说不能控制了. 只控制开关都不行. 一直提示智能家居控制暂时使用不了. 不知道哪里有问题. 百度之后发现, 有些人说是因为延迟过高导致这个提示. 在巴法云控制平台试过直接发开关控制消息, 可以控制灯组.

**Comment by larry-wong** [comment]
从巴法云控制平台可以控制表明此集成已成功将 HASS 同步至巴法云。猫精控制失败可能是巴法云跟猫精之间的同步问题，此集成无法解决，后续可继续观察。
