### ISSUE TITLE
断网后不能自动恢复

### ISSUE THREAD

**Issue by weiyue88** [larry-wong/bemfa#28]
homeassistant断网后bemfa同步的设备离线，但是网络恢复后依旧还在离线状态，不能自动恢复，需要重载插件才可以。能否添加个同步失效的检测，网络恢复后重新订阅？

**Comment by ngyinchew** [comment]
差不多的问题，一天断连一次，都是ping失败后 reconnect 超时，然后巴发云就显示订阅者离线，需要reload那个component

**Comment by larry-wong** [comment]
v1.3.2 版本已经修复重连失败的问题。
