### ISSUE TITLE
不支持老版0.114.4吗？

### ISSUE THREAD

**Issue by sxx1314** [larry-wong/bemfa#3]
由于新版开始不支持html嵌入侧边栏，所以一直没升级。
测试可以hacs安装/通过custom_components安装。没有报错。
```
WARNING (MainThread) [homeassistant.loader] You are using a custom integration for bemfa which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```
但是在集成页面无法搜索到。

**Comment by larry-wong** [comment]
抱歉，手头上暂时没旧版的HA, 可能有些不太兼容。

**Comment by larry-wong** [comment]
抱歉，手头上暂时没旧版的HA, 可能有些不太兼容。

**Comment by sxx1314** [comment]
有没有可能直接加一个读取yaml的配置选项。方便直接通过yaml配置，这样就不用考虑适配集成了，看了一下集成部分应该是2021.6版本之后修改过部分api。

**Comment by wecane** [comment]
@larry-wong 好用，已start，巴法那边对小度风扇和空调已经进行支持了，小爱的空调制冷制热好像也支持了

**Comment by larry-wong** [comment]
> 有没有可能直接加一个读取yaml的配置选项。方便直接通过yaml配置，这样就不用考虑适配集成了，看了一下集成部分应该是2021.6版本之后修改过部分api。

新版的 HA 已经不建议使用 YAML 的配置方式了，因此目前不会考虑支持，建议想办法升级 HA，毕竟新功能还是蛮多的 :)

**Comment by sxx1314** [comment]
直接用nodered解决了。ha不考虑升级，更新的新功能没一个值得花大功夫去升级的，依旧是老一套，但是不兼容太多老插件。
