### ISSUE TITLE
巴法雲 ---> 订阅者：离线

### ISSUE THREAD

**Issue by drkshen** [larry-wong/bemfa#49]
Home Assistant 設備 加入 巴法雲 成功

巴法雲  MQTT 上顯示   订阅者：离线

不過只有 ping 在线
---------------------------
hassping
数值：ping
时间：2024-03-23 15:02:39
订阅者：在线 1
---------------------------

如何修復 订阅者：离线 問題???

**Comment by a652755832** [comment]
同这个问题

**Comment by luckhy2882** [comment]
我大约也是3/22开始无法使用，今日上去巴法云确认所有设备订阅者：离线，只有hassping，数值：ping，订阅者：在线 1，和楼主同样的问题出现，再请帮忙，谢谢。

**Comment by skddyj** [comment]
同出现这个问题，大佬有时间能看看不 @larry-wong

**Comment by LiHang941** [comment]
同这个问题

**Comment by VergLsm** [comment]
一样的问题

**Comment by twfjcn** [comment]
应该是插件同步数据不准确了，自荐的mqtt没问题

**Comment by davidteh1987** [comment]
我的也是，尝试了重装也是不可以😭

**Comment by zt8989** [comment]
应该是过度使用qos2被封了，目前只能换一个账号，然后使用我的git库
https://cloud.bemfa.com/docs/src/mqtt.html
MQTT 支持Qos0 Qos1，支持retian保留消息，不支持qos2，使用qos2会被强制下线，次数过多可造成账号异常无法使用。
