### ISSUE TITLE
没有设备

### ISSUE THREAD

**Issue by leoncoolmoon** [larry-wong/bemfa#5]
安装后把ha的设备（彩灯组）共享出去了，巴法云端mqtt里出现了hassping 以及hass+一长串编号两个设备，但是小米和谷歌里都说没有设备

**Comment by larry-wong** [comment]
此插件的作用是将HA的实体同步至巴法云，如果巴法云后台状态更新正常并且可以控制HA实体，则说明此插件工作正常。
至于小米和谷歌接入可参考巴法云官方文档。
