### ISSUE TITLE
hacs下载存储库一直在转圈

### ISSUE THREAD

**Issue by shzang** [larry-wong/bemfa#50]
今天在内网部署了docker版本的ha，安装完xiaomi iot之后装bemfa，结果一直卡在下载状态，openwrt没做vpn配置，是因为文件在github导致下载失败么，现在用github上下载的源码手动导入到文件夹之后可以在集成完成绑定，但是在hacs的库里不显示bemfa的信息，hacs搜索还是提示下载

**Comment by ipoyang7** [comment]
需要从 release 里面下载

**Comment by shzang** [comment]
感谢回复，提交issues后自己通过检索解决了这个问题，目前能够正常使用了

**Comment by shzang** [comment]
> 需要从 release 里面下载

感谢回复，提交问题后自己通过检索解决了这个问题，目前能够正常使用了
