### ISSUE TITLE
建议在巴法云创建设备时，根据设备属性选择后缀。

### ISSUE THREAD

**Issue by imwyh** [larry-wong/bemfa#7]
巴法云目前开关尾缀是006，灯尾缀是002。我建议如果在hassos中需要同步的实体名字的尾缀是灯，如：吸顶灯，或者尾缀是ligth，那么同步时就设置尾缀为002，其他的尾缀还是006。
用途：叫对小爱可以发命令：关所有的灯，就不会关006的设备

**Comment by larry-wong** [comment]
可以使用 [Switch as X](https://www.home-assistant.io/integrations/switch_as_x/) 将开关转换成灯，再同步至巴法云。
